export default {
    "langs": {
        "en-US": {
            "helpers.localizeDefaultLang": "[instantgram-light] set language: ${LANG_DEFAULT} \n For more information about available languages please check http://thinkbig-company.github.io/instantgram-light",
            "alertWorksOnlyOn": "Works only on instagram.com",
            "alertNotFound": "Did you open any Instagram post? Like for example<br/><div style='text-align:center'><a style='color:black' href='https://www.instagram.com/p/CIGrv1VMBkS/' target='_blank'>https://www.instagram.com/p/CIGrv1VMBkS/</a></div>",
            "modalSettingsTitle": "Settings",
            "modalSettingsAttention": "Attention: You must open this app again for your changes to be applied!",
            "modalSettingsGeneral": "General",
            "modalSettingsGenTitle1": "Enable monetized posts",
            "modalSettingsGenDesc1": "Ad blockers must be deactivated",
            "modalSettingsGenTitle2": "Open download in new tab",
            "modalSettingsGenDesc2": "The download will be opened in a new tab",
            "modalSettingsGenTitle3": "Slideshow on/off",
            "modalSettingsGenDesc3": "Enable or disable the automatic slideshow",
            "modalSettingsGenTitle4": "Change file name format for downloads",
            "modalSettingsGenDesc4": "Change the file name format for the downloads here<br/>The default format is<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
            "modalSettingsStoriesTitle1": "Mute stories",
            "modalSettingsStoriesDesc1": "Stories are muted when opened",
            "modalSettingsStoriesTitle2": "Pause stories when opening",
            "modalSettingsStoriesDesc2": "Stories are paused when opened",
            "modalSettingsStoriesTitle3": "Display stories individually",
            "modalSettingsStoriesDesc3": "Stories are displayed individually when opened",
            "download": "Download",
            "save": "Save",
            "saved": "Saved",
            "close": "Close",
            "consoleWarnOutdatedInfo": "[instantgram-light] is outdated. Please check http://thinkbig-company.github.io/instantgram-light for available updates.",
            "consoleWarnOutdatedVersions": "[instantgram-light] Installed version: ${data.version} | New update: ${data.onlineVersion}",
            "ad": "Sponsored"
        },
        "de-DE": {
            "helpers.localizeDefaultLang": "Ausgewählte Sprache: ${LANG_DEFAULT} \n Weitere Informationen zu den unterstützten Sprachen findest du auf http://thinkbig-company.github.io/instantgram-light",
            "alertWorksOnlyOn": "Funktioniert nur auf instagram.com",
            "alertNotFound": "Hast du einen Instagram Post geöffnet? Zum Beispiel<br/><div style='text-align:center'><a style='color:black' href='https://www.instagram.com/p/CIGrv1VMBkS/' target='_blank'>https://www.instagram.com/p/CIGrv1VMBkS/</a></div>",
            "modalSettingsTitle": "Einstellungen",
            "modalSettingsAttention": "Achtung: Sie müssen diese App erneut öffnen, damit ihre Änderungen übernommen werden!",
            "modalSettingsGeneral": "Allgemein",
            "modalSettingsGenTitle1": "Monetarisierte Beiträge aktivieren",
            "modalSettingsGenDesc1": "Werbeblocker müssen deaktiviert sein",
            "modalSettingsGenTitle2": "Download in neuem Tab öffnen",
            "modalSettingsGenDesc2": "Der Download wird in einem neuen Tab geöffnet",
            "modalSettingsGenTitle3": "Slideshow ein/ausschalten",
            "modalSettingsGenDesc3": "Aktivieren oder deaktivieren Sie die automatische Slideshow",
            "modalSettingsGenTitle4": "Dateinamenformat für Downloads ändern",
            "modalSettingsGenDesc4": "Ändere hier das Dateinamenformat für die Downloads<br/>Das Standardformat ist<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
            "modalSettingsStoriesTitle1": "Stories stummschalten",
            "modalSettingsStoriesDesc1": "Beim öffnen werden Stories stummgeschaltet",
            "modalSettingsStoriesTitle2": "Stories beim öffnen pausieren",
            "modalSettingsStoriesDesc2": "Beim öffnen werden Stories pausiert",
            "modalSettingsStoriesTitle3": "Stories einzeln anzeigen",
            "modalSettingsStoriesDesc3": "Beim öffnen werden Stories einzeln angezeigt",
            "download": "Download",
            "save": "Speichern",
            "saved": "Gespeichert",
            "close": "Schließen",
            "consoleWarnOutdatedInfo": "[instantgram-light] ist veraltet. Bitte besuche die Seite http://thinkbig-company.github.io/instantgram-light für ein Update.",
            "consoleWarnOutdatedVersions": "[instantgram-light] Installierte Version: ${data.version} | Neue Version: ${data.onlineVersion}",
            "ad": "Anzeige"
        },
        "es-AR": {
            "helpers.localizeDefaultLang": "[instantgram-light] establecer idioma: ${LANG_DEFAULT} \n Para más información sobre los idiomas disponibles, consulte http://thinkbig-company.github.io/instantgram-light",
            "alertWorksOnlyOn": "Sólo funciona en instagram.com",
            "alertNotFound": "¿Has abierto algún post de Instagram? Como por ejemplo<br/><div style='text-align:center'><a style='color:black' href='https://www.instagram.com/p/CIGrv1VMBkS/' target='_blank'>https://www.instagram.com/p/CIGrv1VMBkS/</a></div>",
            "modalSettingsTitle": "Ajustes",
            "modalSettingsAttention": "Atención: ¡Debes abrir esta aplicación nuevamente para que se apliquen los cambios!",
            "modalSettingsGeneral": "General",
            "modalSettingsGenTitle1": "Habilitar publicaciones monetizadas",
            "modalSettingsGenDesc1": "Los bloqueadores de publicidad deben estar desactivados",
            "modalSettingsGenTitle2": "Abrir descarga en una nueva pestaña",
            "modalSettingsGenDesc2": "La descarga se abrirá en una nueva pestaña",
            "modalSettingsGenTitle3": "Slideshow on/off",
            "modalSettingsGenDesc3": "Activar/desactivar presentación de diapositivas",
            "modalSettingsGenTitle4": "Cambiar el formato del nombre del archivo para descargas",
            "modalSettingsGenDesc4": "Cambie el formato del nombre de archivo para las descargas aquí<br/>El formato predeterminado es<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
            "modalSettingsStoriesTitle1": "Historias mudas",
            "modalSettingsStoriesDesc1": "Las historias se silencian cuando se abren",
            "modalSettingsStoriesTitle2": "Pausar historias al abrir",
            "modalSettingsStoriesDesc2": "Las historias se pausan cuando se abren.",
            "modalSettingsStoriesTitle3": "Mostrar historias individualmente",
            "modalSettingsStoriesDesc3": "Las historias se muestran individualmente cuando se abren",
            "download": "Descargar",
            "save": "Ahorrar",
            "saved": "Salvado",
            "close": "Cerca",
            "consoleWarnOutdatedInfo": "[instantgram-light] es obsoleto. Consulte en http://thinkbig-company.github.io/instantgram-light las actualizaciones disponibles.",
            "consoleWarnOutdatedVersions": "[instantgram-light] Versión instalada: ${data.version} | Nueva actualización: ${data.onlineVersion}",
            "ad": "Publicidad"
        },
        "pt-BR": {
            "helpers.localizeDefaultLang": "[instantgram-light] idioma configurado: ${LANG_DEFAULT} \npara mais informações sobre os idiomas suportados, acesse http://thinkbig-company.github.io/instantgram-light",
            "alertWorksOnlyOn": "[instantgram-light] somente funciona no instagram.com",
            "alertNotFound": "ops, você está em algum post do instagram? ex:<br/><div style='text-align:center'><a style='color:black' href='https://www.instagram.com/p/CIGrv1VMBkS/' target='_blank'>https://www.instagram.com/p/CIGrv1VMBkS/</a></div>",
            "modalSettingsTitle": "Configurações",
            "modalSettingsAttention": "Atenção: Você deve abrir este aplicativo novamente para que suas alterações sejam aplicadas!",
            "modalSettingsGeneral": "Geral",
            "modalSettingsGenTitle1": "Habilitar postagens monetizadas",
            "modalSettingsGenDesc1": "Os bloqueadores de anúncios devem ser desativados",
            "modalSettingsGenTitle2": "Abrir o download em uma nova guia",
            "modalSettingsGenDesc2": "O download será aberto em uma nova guia",
            "modalSettingsGenTitle3": "Ativação/desativação da apresentação de slides",
            "modalSettingsGenDesc3": "Ativar ou desativar a apresentação automática de slides",
            "modalSettingsGenTitle4": "Alterar o formato do nome do arquivo para downloads",
            "modalSettingsGenDesc4": "Altere o formato do nome do arquivo para os downloads aqui<br/>O formato padrão é<br>{Username}__{Year}-{Month}-{Day}--{Hour}-{Minute}",
            "modalSettingsStoriesTitle1": "Histórias mudas",
            "modalSettingsStoriesDesc1": "As histórias são silenciadas quando abertas",
            "modalSettingsStoriesTitle2": "Pausar histórias ao abrir",
            "modalSettingsStoriesDesc2": "As histórias são pausadas quando abertas",
            "modalSettingsStoriesTitle3": "Exibir histórias individualmente",
            "modalSettingsStoriesDesc3": "As histórias são exibidas individualmente quando abertas",
            "download": "Download",
            "save": "Salvar",
            "saved": "Salvo em",
            "close": "Fechar",
            "consoleWarnOutdatedInfo": "[instantgram-light] está desatualizado. Acesse http://thinkbig-company.github.io/instantgram-light para atualizar",
            "consoleWarnOutdatedVersions": "[instantgram-light] versão local: ${data.version} | nova versão: ${data.onlineVersion}",
            "ad": "Patrocinado"
        }
    }
}